- name: Deploy Petclinic to EC2 instance
  hosts: ec2
  gather_facts: false
  remote_user: ubuntu
  become: true
  tasks:
    - name: Create destination directory
      file:
        path: "/home/ubuntu/apps"
        state: directory

    - name: Copy JAR file to EC2 instance
      copy:
        src: "{{ workspace }}/target/spring-petclinic-3.1.0-SNAPSHOT.jar"
        dest: "/home/ubuntu/apps/spring-petclinic.jar"

    - name: Start Petclinic application on EC2 instance
      command: nohup java -jar "/home/ubuntu/apps/spring-petclinic.jar" > /dev/null 2>&1 &
